# Setup
title:               'Blockbuster Actors'
tagline:             'A Data Story'
url:                 https://raphaellehartwig.github.io/lanyon/
baseurl:             ''
paginate:            5
permalink:           pretty
github:              https://github.com/epfl-ada/ada-2023-project-pinacolada23

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
